# Generated by Django 5.0.14 on 2026-08-27 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_expense', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gst_output_tax', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gst_input_tax_credit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estimated_gst_liability', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('financial_year_start', models.DateField()),
                ('financial_year_end', models.DateField()),
                ('financial_year_gross_receipts', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estimated_income_tax', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_estimates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_start'],
                'unique_together': {('user', 'period_start', 'period_end')},
            },
        ),
    ]
