# Generated by Django 5.0.14 on 2026-08-27 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('invoice_overdue', 'Invoice overdue'), ('invoice_paid', 'Invoice paid'), ('recurring_invoice_generated', 'Recurring invoice generated'), ('webhook_failed', 'Webhook delivery failed')], max_length=40)),
                ('message', models.CharField(max_length=255)),
                ('link_path', models.CharField(blank=True, help_text='Frontend route to link to, e.g. /invoices/12', max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
