# Generated by Django 5.0.14 on 2026-08-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('invoice_overdue', 'Invoice overdue'), ('invoice_paid', 'Invoice paid'), ('recurring_invoice_generated', 'Recurring invoice generated'), ('webhook_failed', 'Webhook delivery failed'), ('referral_reward_granted', 'Referral reward granted')], max_length=40),
        ),
    ]
