# Generated by Django 5.0.14 on 2026-08-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='referral_reward_granted',
            field=models.BooleanField(default=False),
        ),
    ]
