# Generated by Django 5.0.14 on 2026-08-23 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name_snapshot', models.CharField(max_length=255)),
                ('client_email_snapshot', models.EmailField(blank=True, max_length=254)),
                ('client_address_snapshot', models.TextField(blank=True)),
                ('client_country_snapshot', models.CharField(max_length=100)),
                ('client_gstin_snapshot', models.CharField(blank=True, max_length=15)),
                ('invoice_number', models.CharField(editable=False, max_length=32, unique=True)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('currency', models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='INR', max_length=3)),
                ('exchange_rate_to_inr', models.DecimalField(decimal_places=4, default=1, max_digits=12)),
                ('tax_type', models.CharField(choices=[('CGST_SGST', 'CGST + SGST (same state)'), ('IGST', 'IGST (other state)'), ('EXPORT_ZERO_RATED', 'Export of services (zero-rated)')], max_length=20)),
                ('lut_reference', models.CharField(blank=True, max_length=100)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='draft', max_length=10)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/%Y/%m/')),
                ('payment_link_url', models.URLField(blank=True)),
                ('razorpay_payment_link_id', models.CharField(blank=True, max_length=64)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='clients.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issue_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('hsn_sac_code', models.CharField(blank=True, max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tax_rate_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoicing.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_date', models.DateTimeField()),
                ('method', models.CharField(choices=[('razorpay', 'Razorpay'), ('manual', 'Manual')], max_length=10)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('captured', 'Captured'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='invoicing.invoice')),
            ],
        ),
    ]
