# Generated by Django 5.0.14 on 2026-08-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='last_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
