# Generated by Django 5.0.14 on 2026-08-27 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('invoicing', '0002_invoice_last_reminder_sent_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='client_state_snapshot',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='RecurringInvoiceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], max_length=10)),
                ('currency', models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='INR', max_length=3)),
                ('exchange_rate_to_inr', models.DecimalField(decimal_places=4, default=1, max_digits=12)),
                ('due_in_days', models.PositiveIntegerField(default=14)),
                ('next_run_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('auto_send', models.BooleanField(default=False, help_text='If set, the generated invoice is emailed to the client automatically.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_profiles', to='clients.client')),
                ('last_generated_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='invoicing.invoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_run_date'],
            },
        ),
        migrations.CreateModel(
            name='RecurringInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('hsn_sac_code', models.CharField(blank=True, max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tax_rate_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoicing.recurringinvoiceprofile')),
            ],
        ),
    ]
