# Generated by Django 5.0.14 on 2026-08-28 00:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('invoicing', '0003_invoice_client_state_snapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='public_view_token',
            field=models.CharField(editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['user', 'status'], name='invoicing_i_user_id_71cab6_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['user', 'issue_date'], name='invoicing_i_user_id_938612_idx'),
        ),
    ]
