# Generated by Django 5.0.14 on 2026-08-28 00:59

import invoicing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0005_backfill_public_view_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='public_view_token',
            field=models.CharField(default=invoicing.models._generate_public_view_token, editable=False, max_length=64, unique=True),
        ),
    ]
