# Generated by Django 5.0.14 on 2026-08-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_seed_categories_for_existing_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='gst_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='GST you paid on this expense, if any - used for the input tax credit estimate in Reports.', max_digits=12),
        ),
    ]
